# Generated by Django 2.2.8 on 2020-02-03 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='name',
        ),
        migrations.AlterField(
            model_name='channel',
            name='authors',
            field=models.ManyToManyField(related_name='author_channels', to=settings.AUTH_USER_MODEL),
        ),
    ]
