# Generated by Django 2.2.8 on 2020-02-03 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_auto_20200203_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='subject',
        ),
    ]
