# Generated by Django 2.2.8 on 2020-02-03 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_auto_20200203_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='authors',
            field=models.ManyToManyField(blank=True, null=True, related_name='author_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
