# Generated by Django 2.2.8 on 2020-02-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0006_auto_20200203_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='main_channel',
            field=models.BooleanField(default=False),
        ),
    ]
