# Generated by Django 2.2.9 on 2020-02-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0007_channel_main_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
