# Generated by Django 2.2.9 on 2020-02-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0008_auto_20200205_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
