# Generated by Django 2.2.8 on 2020-01-29 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200129_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractiontemplate',
            old_name='profile',
            new_name='user',
        ),
    ]
