# Generated by Django 2.2.8 on 2020-01-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_link', models.CharField(max_length=200)),
                ('post_link', models.CharField(blank=True, max_length=200, null=True)),
                ('notification_type', models.CharField(choices=[('follow', 'follow'), ('like', 'like'), ('command', 'command'), ('dislike', 'dislike')], max_length=10)),
            ],
        ),
    ]
