# Generated by Django 2.2.8 on 2020-01-09 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('channel', 'Channel Follow'), ('user', 'User Follow')], max_length=20)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_account.follow_set+', to='contenttypes.ContentType')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followings', to='account.Profile')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='FollowChannel',
            fields=[
                ('follow_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.Follow')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('account.follow',),
        ),
        migrations.CreateModel(
            name='FollowUser',
            fields=[
                ('follow_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.Follow')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='account.Profile')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('account.follow',),
        ),
    ]
