# Generated by Django 2.2.8 on 2020-01-16 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_followchannel_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='account.Profile')),
            ],
        ),
    ]
