# Generated by Django 2.2.8 on 2020-01-09 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
        ('account', '0002_follow_followchannel_followuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='followchannel',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='channel.Channel'),
        ),
    ]
