# Generated by Django 2.2.8 on 2020-01-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profiletoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletoken',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
