# Generated by Django 2.2.8 on 2020-01-12 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200112_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aaaa', to='account.Profile'),
        ),
        migrations.AlterField(
            model_name='followchannel',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssss', to='channel.Channel'),
        ),
        migrations.AlterField(
            model_name='followuser',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bbbb', to='account.Profile'),
        ),
    ]
