# Generated by Django 2.2.8 on 2020-01-17 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200116_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='type',
            new_name='follow_type',
        ),
    ]
