# Generated by Django 2.2.8 on 2020-02-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200117_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPasswordToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
    ]
