# Generated by Django 2.2.8 on 2020-01-12 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200112_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_followings', to='account.Profile'),
        ),
    ]
